const navItemsDonor = [
    {
        label: "Home",
        href: "/",
    },
    // {
    //     label: "About",
    //     href: "/about",
    // },
    // {
    //     label: "Contact",
    //     href: "/contact",
    // },
    {
        label: "Dashboard",
        href: "/dashboard",
    },
    {
        label: "Create Listing",
        href: "/create-listing",
    },
    {
        label: "Organisations",
        href: "/organisations",
    }
];

const navItemsOrganisation = [
    {
        label: "Home",
        href: "/",
    },
    {
        label: "Organisation Profile",
        href: "/organisation-profile",
    },
    {
        label: "Dashboard",
        href: "/dashboard",
    },
    {
        label: "Organisations",
        href: "/organisations",
    }
];

const dummyOrganisations: OrganisationProfile[] = [
    {
        _id: "org_1",
        clerkId: "clerk_org_1",
        name: "Green Tech Recyclers",
        address: "123 Eco Way, Green City, SG 123456",
        phone: "+65 6123 4567",
        email: "contact@greentech.org",
        website: "www.greentech.org",
        logo: "https://cdn-icons-png.flaticon.com/512/2979/2979632.png",
        description: "We specialize in refurbishing laptops and desktops for educational purposes. Our mission is to bridge the digital divide by providing affordable technology to students in need.",
        needs: ["Laptops", "Desktops", "Monitors"],
        tags: ["Education", "Refurbishing", "Technology"],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        _id: "org_2",
        clerkId: "clerk_org_2",
        name: "Digital Hope Foundation",
        address: "456 Charity Lane, Kindness Town, SG 654321",
        phone: "+65 6234 5678",
        email: "info@digitalhope.org",
        website: "www.digitalhope.org",
        logo: "https://cdn-icons-png.flaticon.com/512/3062/3062331.png",
        description: "Digital Hope Foundation focuses on collecting smartphones and tablets to help low-income families stay connected. We repair and distribute devices to those who cannot afford them.",
        needs: ["Smartphones", "Tablets", "Chargers"],
        tags: ["Community", "Mobile", "Connectivity"],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        _id: "org_3",
        clerkId: "clerk_org_3",
        name: "E-Waste Solutions",
        address: "789 Industrial Park, Tech Hub, SG 987654",
        phone: "+65 6345 6789",
        email: "support@ewastesolutions.com",
        website: "www.ewastesolutions.com",
        logo: "https://cdn-icons-png.flaticon.com/512/1598/1598196.png",
        description: "We are committed to environmentally friendly e-waste disposal and recycling. We handle all types of electronic waste, ensuring safe and responsible processing.",
        needs: ["Printers", "Scanners", "Cables"],
        tags: ["Recycling", "Environment", "Sustainability"],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        _id: "org_4",
        clerkId: "clerk_org_4",
        name: "Computer Aid International",
        address: "321 Global Ave, World Center, SG 112233",
        phone: "+65 6456 7890",
        email: "hello@computeraid.org",
        website: "www.computeraid.org",
        logo: "https://cdn-icons-png.flaticon.com/512/2331/2331970.png",
        description: "Computer Aid International works globally to provide IT equipment to developing countries. We accept donations of working computers and IT accessories.",
        needs: ["Laptops", "Keyboards", "Mice"],
        tags: ["International", "Aid", "Global"],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        _id: "org_5",
        clerkId: "clerk_org_5",
        name: "Tech for Seniors",
        address: "654 Silver Street, Elderly Care, SG 445566",
        phone: "+65 6567 8901",
        email: "contact@techforseniors.sg",
        website: "www.techforseniors.sg",
        logo: "https://cdn-icons-png.flaticon.com/512/2784/2784403.png",
        description: "We help seniors stay connected with their loved ones by providing them with easy-to-use tablets and smartphones. We also offer training sessions.",
        needs: ["Tablets", "Smartphones"],
        tags: ["Seniors", "Community", "Training"],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        _id: "org_6",
        clerkId: "clerk_org_6",
        name: "Green Earth Recyclers",
        address: "987 Nature Blvd, Eco Park, SG 778899",
        phone: "+65 6678 9012",
        email: "info@greenearth.com",
        website: "www.greenearth.com",
        logo: "https://cdn-icons-png.flaticon.com/512/9607/9607650.png",
        description: "Green Earth Recyclers is dedicated to zero-waste solutions. We recycle all forms of electronic waste and repurpose usable parts for new devices.",
        needs: ["Batteries", "Circuit Boards", "Old Electronics"],
        tags: ["Zero Waste", "Recycling", "Environment"],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        _id: "org_7",
        clerkId: "clerk_org_7",
        name: "ReConnect SG",
        address: "88 Migrant Lane, Community Hub, SG 554433",
        phone: "+65 6789 0123",
        email: "help@reconnect.sg",
        website: "www.reconnect.sg",
        logo: "https://cdn-icons-png.flaticon.com/512/3209/3209955.png",
        description: "ReConnect SG collects used smartphones to provide to migrant workers, helping them stay connected with their families back home.",
        needs: ["Smartphones", "Chargers", "Power Banks"],
        tags: ["Migrant Support", "Community", "Communication"],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        _id: "org_8",
        clerkId: "clerk_org_8",
        name: "EcoKids Coding",
        address: "42 Learning Drive, Innovation Park, SG 223344",
        phone: "+65 6890 1234",
        email: "start@ecokids.sg",
        website: "www.ecokids.sg",
        logo: "https://cdn-icons-png.flaticon.com/512/3069/3069172.png",
        description: "We run coding workshops for underprivileged children. We need working laptops to ensure every child has a device to learn on.",
        needs: ["Laptops", "Mice", "Headphones"],
        tags: ["Education", "Children", "Coding"],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        _id: "org_9",
        clerkId: "clerk_org_9",
        name: "Circular Electronics",
        address: "101 Cycle Road, Industrial Estate, SG 998877",
        phone: "+65 6901 2345",
        email: "recycle@circularelectronics.com",
        website: "www.circularelectronics.com",
        logo: "https://cdn-icons-png.flaticon.com/512/1675/1675168.png",
        description: "Specializing in advanced recycling, we extract precious metals from non-functional electronics to reduce mining demand.",
        needs: ["Broken Electronics", "Old Cables", "Motherboards"],
        tags: ["Advanced Recycling", "Sustainability", "Materials"],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    }
];

const dummyMatches: Listing[] = [
    {
        _id: "match_1",
        clerkId: "user_123",
        title: "2015 MacBook Pro 15\"",
        description: "Well-used machine. Heavy scratches on bottom case and some sticker residue on the lid. Battery says 'Service Recommended' but works plugged in.",
        address: "123 Orchard Road, Singapore",
        photo: "https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?q=80&w=1000&auto=format&fit=crop",
        needsRepair: true,
        resolved: true,
        notes: "Charger cable is frayed but works. [Volunteer Notes]: Picked up on Tuesday.",
        tags: ["Laptop", "Apple", "Repair"],
        createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
        matchedOrganisationId: "org_1",
    },
    {
        _id: "match_2",
        clerkId: "user_456",
        title: "Lenovo ThinkPad T480",
        description: "Workhorse laptop. Trackpad is worn shiny, 'E' key is loose. Screen has a small bright spot. Good for parts or if you have a spare keyboard.",
        address: "456 Tampines Ave, Singapore",
        photo: "https://images.unsplash.com/photo-1588702547919-26089e690ecc?auto=format&fit=crop&w=800",
        needsRepair: true,
        resolved: true,
        notes: "[Volunteer Notes]: Collected for refurbishment.",
        tags: ["Laptop", "Lenovo", "Parts"],
        createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
        matchedOrganisationId: "org_1",
    },
    {
        _id: "match_3",
        clerkId: "user_789",
        title: "Dell XPS 13 (9360)",
        description: "Visible dent on the top right corner of the chassis. Hinge is slightly loose. Fan gets loud under load.",
        address: "789 Jurong West, Singapore",
        photo: "https://images.unsplash.com/photo-1593642702821-c8da6771f0c6?auto=format&fit=crop&w=800&q=80",
        needsRepair: true,
        resolved: false,
        notes: "Comes with original box.",
        tags: ["Laptop", "Dell", "Worn"],
        createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
        matchedOrganisationId: "org_1",
    },
    {
        _id: "match_4",
        clerkId: "user_101",
        title: "HP Stream 14",
        description: "Plastic casing has some cracks near the ports. Very slow, good for basic browsing only or stripping for parts.",
        address: "321 Bishan St, Singapore",
        photo: "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&w=800",
        needsRepair: false,
        resolved: true,
        notes: "[Volunteer Notes]: Delivered to warehouse.",
        tags: ["Laptop", "HP", "Old"],
        createdAt: new Date(Date.now() - 86400000 * 10).toISOString(),
        matchedOrganisationId: "org_1",
    },
    {
        _id: "match_5",
        clerkId: "user_202",
        title: "Acer Aspire 5",
        description: "Left hinge is broken and screen wobbles. System runs fine but needs careful opening/closing.",
        address: "555 Serangoon Rd, Singapore",
        photo: "https://images.unsplash.com/photo-1580522154071-c6ca47a859ad?auto=format&fit=crop&w=800",
        needsRepair: true,
        resolved: true,
        notes: "[Volunteer Notes]: Parts harvested.",
        tags: ["Laptop", "Acer", "Broken Hinge"],
        createdAt: new Date(Date.now() - 86400000 * 12).toISOString(),
        matchedOrganisationId: "org_1",
    },
    {
        _id: "match_6",
        clerkId: "user_303",
        title: "Microsoft Surface Laptop 2",
        description: "Alcantara fabric on keyboard deck is stained and worn. Battery holds 50% charge. No charger included.",
        address: "888 Bedok North, Singapore",
        photo: "https://images.unsplash.com/photo-1515378791036-0648a3ef77b2?auto=format&fit=crop&w=800",
        needsRepair: false,
        resolved: false,
        notes: "Please bring your own charger to test.",
        tags: ["Laptop", "Surface", "Worn"],
        createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
        matchedOrganisationId: "org_1",
    },
    {
        _id: "match_7",
        clerkId: "user_404",
        title: "Asus ZenBook 13",
        description: "Screen flickers occasionally, might be a loose cable. Exterior has minor dents.",
        address: "999 Woodlands Dr, Singapore",
        photo: "https://images.unsplash.com/photo-1593642532973-d31b6557fa68?auto=format&fit=crop&w=800",
        needsRepair: true,
        resolved: true,
        notes: "[Volunteer Notes]: Sent for screen repair evaluation.",
        tags: ["Laptop", "Asus", "Screen Issue"],
        createdAt: new Date(Date.now() - 86400000 * 7).toISOString(),
        matchedOrganisationId: "org_1",
    }
];

export { navItemsDonor, navItemsOrganisation, dummyOrganisations, dummyMatches };
